SELECT * FROM CADASTRO
DELETE  FROM CADASTRO

SELECT * FROM TOKEN

SELECT * FROM SECRETARIA
DELETE FROM SECRETARIA

SELECT * FROM CADASTRO

INSERT INTO SECRETARIA (NOME_SECRETARIA, SENHA_SECRETARIA) VALUES('vc', '123')
